<a href="https://colab.research.google.com/github/vatsalvasani/CE155_ML/blob/main/LAB%207/CE155_LABWORK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **LAB : 7**
### **LABWORK**

In [43]:
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [44]:
from google.colab import drive
drive.mount("/content/drive")
data = pd.read_csv("/content/drive/MyDrive/sem 6/ML/LAB 7/BuyComputer.csv")
print("\nData :\n",data)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Data :
       User ID  Age  EstimatedSalary  Purchased
0    15624510   19            19000          0
1    15810944   35            20000          0
2    15668575   26            43000          0
3    15603246   27            57000          0
4    15804002   19            76000          0
..        ...  ...              ...        ...
395  15691863   46            41000          1
396  15706071   51            23000          1
397  15654296   50            20000          1
398  15755018   36            33000          0
399  15594041   49            36000          1

[400 rows x 4 columns]


In [45]:
data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [46]:
features_Cols=['Age' ,'EstimatedSalary']
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values


In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(x,y,test_size=0.1)


In [48]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [49]:
def sigmoid(z):
  sig = 1/(1+exp(-z))
  return sig

In [50]:
def standardize(X_tr):
    for i in range(shape(X_tr)[1]):
        X_tr[:,i] = (X_tr[:,i] - np.mean(X_tr[:,i]))/np.std(X_tr[:,i])

In [51]:
def F1_score(y,y_hat):
    tp,tn,fp,fn = 0,0,0,0
    for i in range(len(y)):
        if y[i] == 1 and y_hat[i] == 1:
            tp += 1
        elif y[i] == 1 and y_hat[i] == 0:
            fn += 1
        elif y[i] == 0 and y_hat[i] == 1:
            fp += 1
        elif y[i] == 0 and y_hat[i] == 0:
            tn += 1
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    f1_score = 2*precision*recall/(precision+recall)
    return f1_score

# **MODEL**

In [52]:
from numpy import log,dot,exp,shape
class LogisticRegression:
    def sigmoid(self,z):
        sig = 1/(1+exp(-z))
        return sig
    def initialize(self,X):
        weights = np.zeros((shape(X)[1]+1,1))
        X = np.c_[np.ones((shape(X)[0],1)),X]
        return weights,X
    def fit(self,X,y,alpha=0.002,iter=3000):
        weights,X = self.initialize(X)
        # Binary Cross Entropy Loss
        def cost(theta):
            print(theta)
            # print("vatsal")
            z = dot(X,theta)
            # print(z)
            # print("vatsal")
            # print(X)
            cost0 = y.T.dot(log(self.sigmoid(z)))
            cost1 = (1-y).T.dot(log(1-self.sigmoid(z)))
            cost = -((cost1 + cost0))/len(y)
            return cost
            # MSE LOSS
        # def cost(theta):
        #   z = dot(X,theta)
        #   cost = (self.sigmoid(z) - y)**2;
        #   return cost
        cost_list = np.zeros(iter,)
        for i in range(iter):
            weights = weights - alpha*dot(X.T,self.sigmoid(dot(X,weights))-np.reshape(y,(len(y),1)))
            cost_list[i] = cost(weights)
        self.weights = weights
        return cost_list
    def predict(self,X):
        z = dot(self.initialize(X)[1],self.weights)
        lis = []
        for i in self.sigmoid(z):
            if i>0.5:
                lis.append(1)
            else:
                lis.append(0)
        return lis

In [53]:
standardize(X_train)
standardize(X_test)
obj1 = LogisticRegression()

In [54]:
model= obj1.fit(X_train,y_train)
print("Indivisual Cost :")
print(model)
print("Total Cost :")
print(sum(model))
y_pred = obj1.predict(X_test)
y_tr = obj1.predict(X_train)

Streaming output truncated to the last 5000 lines.
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064]
 [ 2.37356754]
 [ 1.16992422]]
[[-1.15571064

In [55]:
f1_score_tr = F1_score(y_train,y_tr)
f1_score_te = F1_score(y_test,y_pred)
print("Performance Using Defining The Model On Training Data")
print(f1_score_tr)
print("Performance Using Defining The Model On Test Data")
print(f1_score_te)

Performance Using Defining The Model On Training Data
0.7586206896551724
Performance Using Defining The Model On Test Data
0.7999999999999999


In [56]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
LR = LogisticRegression(random_state = 0)
LR.fit(X_train,y_train)
y_pred=LR.predict(X_test)
print("Performance Using InBuilt LogisticRegression Model On Test Data")
print(f1_score(y_test,y_pred))

Performance Using InBuilt LogisticRegression Model On Test Data
0.7999999999999999
