<a href="https://colab.research.google.com/github/vatsalvasani/CE155_ML/blob/main/LAB%207/CE155_EXERCISE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **LAB : 7**
### **EXERCISE**

In [15]:
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [16]:
from google.colab import drive
drive.mount("/content/drive")
data = pd.read_csv("/content/drive/MyDrive/sem 6/ML/LAB 7/BuyComputer.csv")
print("\nData :\n",data)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Data :
       User ID  Age  EstimatedSalary  Purchased
0    15624510   19            19000          0
1    15810944   35            20000          0
2    15668575   26            43000          0
3    15603246   27            57000          0
4    15804002   19            76000          0
..        ...  ...              ...        ...
395  15691863   46            41000          1
396  15706071   51            23000          1
397  15654296   50            20000          1
398  15755018   36            33000          0
399  15594041   49            36000          1

[400 rows x 4 columns]


In [17]:
data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [18]:
features_Cols=['Age' ,'EstimatedSalary']
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

print(x)
print(y)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(x,y,test_size=0.1)
print(X_train)
print("vatsal")
print(X_test)
print("vatsal")
print(y_train)
print("vatsal")
print(y_test)

[[    31  76000]
 [    48  35000]
 [    37  33000]
 [    35  38000]
 [    57 122000]
 [    41  71000]
 [    23  48000]
 [    27  20000]
 [    38  50000]
 [    44  39000]
 [    24  84000]
 [    43 129000]
 [    35  91000]
 [    53 143000]
 [    46  59000]
 [    40  71000]
 [    48  41000]
 [    27  96000]
 [    25  79000]
 [    53  34000]
 [    40  57000]
 [    58 101000]
 [    26  52000]
 [    42  64000]
 [    46 117000]
 [    40  60000]
 [    60  42000]
 [    47 105000]
 [    24  23000]
 [    45  79000]
 [    53  72000]
 [    31  58000]
 [    39 122000]
 [    26  17000]
 [    42  65000]
 [    26  15000]
 [    25  87000]
 [    39  61000]
 [    35  75000]
 [    20  36000]
 [    47  20000]
 [    30 116000]
 [    41  30000]
 [    59 130000]
 [    59 143000]
 [    51 134000]
 [    31  66000]
 [    42  54000]
 [    27  58000]
 [    42 108000]
 [    27  89000]
 [    29  75000]
 [    35  61000]
 [    51  23000]
 [    31  71000]
 [    31  34000]
 [    41  59000]
 [    38 112000]
 [    41  5100

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print("vatsal")
print(X_test)
print("vatsal")
print(y_train)
print("vatsal")
print(y_test)

[[-0.65653115  0.16085383]
 [ 0.96231278 -1.03041685]
 [-0.08517447 -1.08852762]
 [-0.27562669 -0.94325071]
 [ 1.81934779  1.49740142]
 [ 0.29572998  0.01557691]
 [-1.41834005 -0.65269688]
 [-1.0374356  -1.46624759]
 [ 0.01005165 -0.59458612]
 [ 0.58140832 -0.91419532]
 [-1.32311394  0.39329688]
 [ 0.48618221  1.70078909]
 [-0.27562669  0.59668456]
 [ 1.43844334  2.10756445]
 [ 0.77186055 -0.33308768]
 [ 0.20050387  0.01557691]
 [ 0.96231278 -0.85608456]
 [-1.0374356   0.74196147]
 [-1.22788782  0.24801997]
 [ 1.43844334 -1.05947224]
 [ 0.20050387 -0.39119844]
 [ 1.91457391  0.88723839]
 [-1.13266171 -0.53647535]
 [ 0.3909561  -0.18781076]
 [ 0.77186055  1.3521245 ]
 [ 0.20050387 -0.30403229]
 [ 2.10502613 -0.82702918]
 [ 0.86708666  1.00345992]
 [-1.32311394 -1.37908144]
 [ 0.67663444  0.24801997]
 [ 1.43844334  0.0446323 ]
 [-0.65653115 -0.36214306]
 [ 0.10527776  1.49740142]
 [-1.13266171 -1.55341374]
 [ 0.3909561  -0.15875538]
 [-1.13266171 -1.6115245 ]
 [-1.22788782  0.48046303]
 

In [21]:
def sigmoid(z):
  sig = 1/(1+exp(-z))
  return sig

In [22]:
def standardize(X_tr):
    for i in range(shape(X_tr)[1]):
        X_tr[:,i] = (X_tr[:,i] - np.mean(X_tr[:,i]))/np.std(X_tr[:,i])

In [23]:
def F1_score(y,y_hat):
    tp,tn,fp,fn = 0,0,0,0
    for i in range(len(y)):
        if y[i] == 1 and y_hat[i] == 1:
            tp += 1
        elif y[i] == 1 and y_hat[i] == 0:
            fn += 1
        elif y[i] == 0 and y_hat[i] == 1:
            fp += 1
        elif y[i] == 0 and y_hat[i] == 0:
            tn += 1
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    f1_score = 2*precision*recall/(precision+recall)
    return f1_score

In [24]:
from numpy import log,dot,exp,shape
class LogisticRegression:
    def sigmoid(self,z):
        sig = 1/(1+exp(-z))
        return sig
    def initialize(self,X):
        weights = np.zeros((shape(X)[1]+1,1))
        X = np.c_[np.ones((shape(X)[0],1)),X]
        return weights,X
    def fit(self,X,y,alpha=0.002,iter=3000):
        weights,X = self.initialize(X)
        def cost(theta):
            z = dot(X,theta)
            cost0 = y.T.dot(log(self.sigmoid(z)))
            cost1 = (1-y).T.dot(log(1-self.sigmoid(z)))
            cost = -((cost1 + cost0))/len(y)
            return cost
        cost_list = np.zeros(iter,)
        for i in range(iter):
            weights = weights - alpha*dot(X.T,self.sigmoid(dot(X,weights))-np.reshape(y,(len(y),1)))
            cost_list[i] = cost(weights)
        self.weights = weights
        return cost_list
    def predict(self,X):
        z = dot(self.initialize(X)[1],self.weights)
        lis = []
        for i in self.sigmoid(z):
            if i>0.5:
                lis.append(1)
            else:
                lis.append(0)
        return lis

In [25]:
standardize(X_train)
standardize(X_test)
obj1 = LogisticRegression()

In [26]:
model= obj1.fit(X_train,y_train)
print("Indivisual Cost :")
print(model)
print("Total Cost :")
print(sum(model))
y_pred = obj1.predict(X_test)
y_tr = obj1.predict(X_train)

Indivisual Cost :
[0.60161842 0.54214487 0.50185276 ... 0.33881229 0.33881229 0.33881229]
Total Cost :
1018.4611505746325


In [27]:
f1_score_tr = F1_score(y_train,y_tr)
f1_score_te = F1_score(y_test,y_pred)
print("Performance Using Defining The Model On Training Data")
print(f1_score_tr)
print("Performance Using Defining The Model On Test Data")
print(f1_score_te)

Performance Using Defining The Model On Training Data
0.792
Performance Using Defining The Model On Test Data
0.72


In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
LR = LogisticRegression(random_state = 155)
LR.fit(X_train,y_train)
y_pred=LR.predict(X_test)
print("Performance Using InBuilt LogisticRegression Model On Test Data")
print(f1_score(y_test,y_pred))

Performance Using InBuilt LogisticRegression Model On Test Data
0.72
