<a href="https://colab.research.google.com/github/vatsalvasani/CE155_ML/blob/main/LAB%207/CE155_LABWORK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **LAB : 7**
### **LABWORK**

In [15]:
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [16]:
from google.colab import drive
drive.mount("/content/drive")
data = pd.read_csv("/content/drive/MyDrive/sem 6/ML/LAB 7/BuyComputer.csv")
print("\nData :\n",data)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Data :
       User ID  Age  EstimatedSalary  Purchased
0    15624510   19            19000          0
1    15810944   35            20000          0
2    15668575   26            43000          0
3    15603246   27            57000          0
4    15804002   19            76000          0
..        ...  ...              ...        ...
395  15691863   46            41000          1
396  15706071   51            23000          1
397  15654296   50            20000          1
398  15755018   36            33000          0
399  15594041   49            36000          1

[400 rows x 4 columns]


In [17]:
data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [18]:
features_Cols=['Age' ,'EstimatedSalary']
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

print(x)
print(y)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(x,y,test_size=0.1)
print(X_train)
print("vatsal")
print(X_test)
print("vatsal")
print(y_train)
print("vatsal")
print(y_test)

[[    41  72000]
 [    24  23000]
 [    59 143000]
 [    40  57000]
 [    49  28000]
 [    26  80000]
 [    56 104000]
 [    49  88000]
 [    24  89000]
 [    41  63000]
 [    35  38000]
 [    47 107000]
 [    35  91000]
 [    24  58000]
 [    48  41000]
 [    32  18000]
 [    37  77000]
 [    24  27000]
 [    37  71000]
 [    28  44000]
 [    18  52000]
 [    46  96000]
 [    26  52000]
 [    32 150000]
 [    49  74000]
 [    54 108000]
 [    52 138000]
 [    41  52000]
 [    46  22000]
 [    45  79000]
 [    42  64000]
 [    47 113000]
 [    35  72000]
 [    56  60000]
 [    29  47000]
 [    35  75000]
 [    30 107000]
 [    19  85000]
 [    50  44000]
 [    39  75000]
 [    39  61000]
 [    25  33000]
 [    28 123000]
 [    20  82000]
 [    46  28000]
 [    47  51000]
 [    36  75000]
 [    35  79000]
 [    31  66000]
 [    47  25000]
 [    31  15000]
 [    27  57000]
 [    57  60000]
 [    22  63000]
 [    28  59000]
 [    47  23000]
 [    48  96000]
 [    46  32000]
 [    48  2900

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print("vatsal")
print(X_test)
print("vatsal")
print(y_train)
print("vatsal")
print(y_test)

[[ 0.31814344  0.05448069]
 [-1.28303901 -1.38205055]
 [ 2.01351309  2.13598515]
 [ 0.22395624 -0.38527377]
 [ 1.07164106 -1.23546573]
 [-1.0946646   0.28901641]
 [ 1.73095148  0.99262355]
 [ 1.07164106  0.52355212]
 [-1.28303901  0.55286908]
 [ 0.31814344 -0.20937199]
 [-0.24697978 -0.94229609]
 [ 0.88326666  1.08057444]
 [-0.24697978  0.61150301]
 [-1.28303901 -0.35595681]
 [ 0.97745386 -0.8543452 ]
 [-0.52954138 -1.52863537]
 [-0.05860537  0.20106551]
 [-1.28303901 -1.2647827 ]
 [-0.05860537  0.02516373]
 [-0.9062902  -0.76639431]
 [-1.84816222 -0.53185859]
 [ 0.78907945  0.75808783]
 [-1.0946646  -0.53185859]
 [-0.52954138  2.3412039 ]
 [ 1.07164106  0.11311462]
 [ 1.54257708  1.1098914 ]
 [ 1.35420267  1.98940033]
 [ 0.31814344 -0.53185859]
 [ 0.78907945 -1.41136752]
 [ 0.69489225  0.25969944]
 [ 0.41233064 -0.18005502]
 [ 0.88326666  1.25647622]
 [-0.24697978  0.05448069]
 [ 1.73095148 -0.29732288]
 [-0.81210299 -0.67844341]
 [-0.24697978  0.14243158]
 [-0.71791579  1.08057444]
 

In [21]:
def sigmoid(z):
  sig = 1/(1+exp(-z))
  return sig

In [22]:
def standardize(X_tr):
    for i in range(shape(X_tr)[1]):
        X_tr[:,i] = (X_tr[:,i] - np.mean(X_tr[:,i]))/np.std(X_tr[:,i])

In [23]:
def F1_score(y,y_hat):
    tp,tn,fp,fn = 0,0,0,0
    for i in range(len(y)):
        if y[i] == 1 and y_hat[i] == 1:
            tp += 1
        elif y[i] == 1 and y_hat[i] == 0:
            fn += 1
        elif y[i] == 0 and y_hat[i] == 1:
            fp += 1
        elif y[i] == 0 and y_hat[i] == 0:
            tn += 1
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    f1_score = 2*precision*recall/(precision+recall)
    return f1_score

# **MODEL**

In [24]:
from numpy import log,dot,exp,shape
class LogisticRegression:
    def sigmoid(self,z):
        sig = 1/(1+exp(-z))
        return sig
    def initialize(self,X):
        weights = np.zeros((shape(X)[1]+1,1))
        X = np.c_[np.ones((shape(X)[0],1)),X]
        return weights,X
    def fit(self,X,y,alpha=0.002,iter=3000):
        weights,X = self.initialize(X)
        # Binary Cross Entropy Loss
        def cost(theta):
            print(theta)
            # print("vatsal")
            z = dot(X,theta)
            # print(z)
            # print("vatsal")
            # print(X)
            cost0 = y.T.dot(log(self.sigmoid(z)))
            cost1 = (1-y).T.dot(log(1-self.sigmoid(z)))
            cost = -((cost1 + cost0))/len(y)
            return cost
            # MSE LOSS
        # def cost(theta):
        #   z = dot(X,theta)
        #   cost = (self.sigmoid(z) - y)**2;
        #   return cost
        cost_list = np.zeros(iter,)
        for i in range(iter):
            weights = weights - alpha*dot(X.T,self.sigmoid(dot(X,weights))-np.reshape(y,(len(y),1)))
            cost_list[i] = cost(weights)
        self.weights = weights
        return cost_list
    def predict(self,X):
        z = dot(self.initialize(X)[1],self.weights)
        lis = []
        for i in self.sigmoid(z):
            if i>0.5:
                lis.append(1)
            else:
                lis.append(0)
        return lis

In [25]:
standardize(X_train)
standardize(X_test)
obj1 = LogisticRegression()

In [26]:
model= obj1.fit(X_train,y_train)
print("Indivisual Cost :")
print(model)
print("Total Cost :")
print(sum(model))
y_pred = obj1.predict(X_test)
y_tr = obj1.predict(X_train)

Streaming output truncated to the last 5000 lines.
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172]
 [ 2.48199685]
 [ 1.32532991]]
[[-1.15852172

In [27]:
f1_score_tr = F1_score(y_train,y_tr)
f1_score_te = F1_score(y_test,y_pred)
print("Performance Using Defining The Model On Training Data")
print(f1_score_tr)
print("Performance Using Defining The Model On Test Data")
print(f1_score_te)

Performance Using Defining The Model On Training Data
0.7717842323651453
Performance Using Defining The Model On Test Data
0.6956521739130435


In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
LR = LogisticRegression(random_state = 0)
LR.fit(X_train,y_train)
y_pred=LR.predict(X_test)
print("Performance Using InBuilt LogisticRegression Model On Test Data")
print(f1_score(y_test,y_pred))

Performance Using InBuilt LogisticRegression Model On Test Data
0.6956521739130435
