<a href="https://colab.research.google.com/github/vatsalvasani/CE155_ML/blob/main/LAB%207/CE155_LABWORK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **LAB : 7**
### **LABWORK**

In [1]:
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [2]:
from google.colab import drive
drive.mount("/content/drive")
data = pd.read_csv("/content/drive/MyDrive/sem 6/ML/LAB 7/BuyComputer.csv")
print("\nData :\n",data)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Data :
       User ID  Age  EstimatedSalary  Purchased
0    15624510   19            19000          0
1    15810944   35            20000          0
2    15668575   26            43000          0
3    15603246   27            57000          0
4    15804002   19            76000          0
..        ...  ...              ...        ...
395  15691863   46            41000          1
396  15706071   51            23000          1
397  15654296   50            20000          1
398  15755018   36            33000          0
399  15594041   49            36000          1

[400 rows x 4 columns]


In [3]:
data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [4]:
features_Cols=['Age' ,'EstimatedSalary']
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

print(x)
print(y)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(x,y,test_size=0.1)
print(X_train)
print("vatsal")
print(X_test)
print("vatsal")
print(y_train)
print("vatsal")
print(y_test)

[[    35 147000]
 [    29  47000]
 [    42  65000]
 [    36  99000]
 [    34  72000]
 [    45  32000]
 [    53 104000]
 [    30 116000]
 [    52  38000]
 [    35  59000]
 [    32 150000]
 [    46  22000]
 [    58  47000]
 [    23  63000]
 [    42  64000]
 [    33 113000]
 [    39  61000]
 [    18  52000]
 [    53 143000]
 [    29  61000]
 [    55 125000]
 [    58 144000]
 [    60  34000]
 [    28  32000]
 [    48 131000]
 [    36  50000]
 [    59 143000]
 [    42 108000]
 [    45  22000]
 [    31  68000]
 [    40  57000]
 [    39  77000]
 [    35  65000]
 [    42  54000]
 [    39  75000]
 [    21  68000]
 [    41  30000]
 [    52  21000]
 [    59  88000]
 [    27  58000]
 [    25  79000]
 [    42  80000]
 [    38  80000]
 [    56  60000]
 [    19  21000]
 [    22  27000]
 [    52  90000]
 [    40  59000]
 [    34  43000]
 [    32 117000]
 [    33  31000]
 [    48 119000]
 [    37  71000]
 [    27  84000]
 [    37 144000]
 [    41  72000]
 [    26  15000]
 [    51  23000]
 [    26 11800

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print("vatsal")
print(X_test)
print("vatsal")
print(y_train)
print("vatsal")
print(y_test)

[[-0.25672895  2.33983479]
 [-0.8225805  -0.66530443]
 [ 0.4034312  -0.12437937]
 [-0.16242035  0.89736796]
 [-0.35103754  0.08598037]
 [ 0.68635698 -1.11607531]
 [ 1.44082572  1.04762492]
 [-0.72827191  1.40824163]
 [ 1.34651713 -0.93576696]
 [-0.25672895 -0.30468773]
 [-0.53965473  2.42998896]
 [ 0.78066557 -1.41658924]
 [ 1.91236869 -0.66530443]
 [-1.38843206 -0.18448216]
 [ 0.4034312  -0.15443077]
 [-0.44534613  1.31808745]
 [ 0.12050542 -0.24458494]
 [-1.85997502 -0.51504747]
 [ 1.44082572  2.21962922]
 [-0.8225805  -0.24458494]
 [ 1.62944291  1.67870416]
 [ 1.91236869  2.24968061]
 [ 2.10098587 -1.05597253]
 [-0.9168891  -1.11607531]
 [ 0.96928276  1.85901251]
 [-0.16242035 -0.57515026]
 [ 2.00667728  2.21962922]
 [ 0.4034312   1.16783049]
 [ 0.68635698 -1.41658924]
 [-0.63396332 -0.0342252 ]
 [ 0.21481402 -0.36479051]
 [ 0.12050542  0.23623733]
 [-0.25672895 -0.12437937]
 [ 0.4034312  -0.45494469]
 [ 0.12050542  0.17613455]
 [-1.57704925 -0.0342252 ]
 [ 0.30912261 -1.1761781 ]
 

In [7]:
def sigmoid(z):
  sig = 1/(1+exp(-z))
  return sig

In [8]:
def standardize(X_tr):
    for i in range(shape(X_tr)[1]):
        X_tr[:,i] = (X_tr[:,i] - np.mean(X_tr[:,i]))/np.std(X_tr[:,i])

In [9]:
def F1_score(y,y_hat):
    tp,tn,fp,fn = 0,0,0,0
    for i in range(len(y)):
        if y[i] == 1 and y_hat[i] == 1:
            tp += 1
        elif y[i] == 1 and y_hat[i] == 0:
            fn += 1
        elif y[i] == 0 and y_hat[i] == 1:
            fp += 1
        elif y[i] == 0 and y_hat[i] == 0:
            tn += 1
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    f1_score = 2*precision*recall/(precision+recall)
    return f1_score

# **MODEL**

In [10]:
from numpy import log,dot,exp,shape
class LogisticRegression:
    def sigmoid(self,z):
        sig = 1/(1+exp(-z))
        return sig
    def initialize(self,X):
        weights = np.zeros((shape(X)[1]+1,1))
        X = np.c_[np.ones((shape(X)[0],1)),X]
        return weights,X
    def fit(self,X,y,alpha=0.002,iter=3000):
        weights,X = self.initialize(X)
        # Binary Cross Entropy Loss
        def cost(theta):
            print(theta)
            # print("vatsal")
            z = dot(X,theta)
            # print(z)
            # print("vatsal")
            # print(X)
            cost0 = y.T.dot(log(self.sigmoid(z)))
            cost1 = (1-y).T.dot(log(1-self.sigmoid(z)))
            cost = -((cost1 + cost0))/len(y)
            return cost
            # MSE LOSS
        # def cost(theta):
        #   z = dot(X,theta)
        #   cost = (self.sigmoid(z) - y)**2;
        #   return cost
        cost_list = np.zeros(iter,)
        for i in range(iter):
            weights = weights - alpha*dot(X.T,self.sigmoid(dot(X,weights))-np.reshape(y,(len(y),1)))
            cost_list[i] = cost(weights)
        self.weights = weights
        return cost_list
    def predict(self,X):
        z = dot(self.initialize(X)[1],self.weights)
        lis = []
        for i in self.sigmoid(z):
            if i>0.5:
                lis.append(1)
            else:
                lis.append(0)
        return lis

In [11]:
standardize(X_train)
standardize(X_test)
obj1 = LogisticRegression()

In [12]:
print(X_train)
print(y_train)
model= obj1.fit(X_train,y_train)
print("Indivisual Cost :")
print(model)
print("Total Cost :")
print(sum(model))
y_pred = obj1.predict(X_test)
y_tr = obj1.predict(X_train)

Streaming output truncated to the last 5000 lines.
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366]
 [ 2.42237055]
 [ 1.10271999]]
[[-1.17054366

In [13]:
f1_score_tr = F1_score(y_train,y_tr)
f1_score_te = F1_score(y_test,y_pred)
print("Performance Using Defining The Model On Training Data")
print(f1_score_tr)
print("Performance Using Defining The Model On Test Data")
print(f1_score_te)

Performance Using Defining The Model On Training Data
0.7659574468085107
Performance Using Defining The Model On Test Data
0.8125


In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
LR = LogisticRegression(random_state = 0)
LR.fit(X_train,y_train)
y_pred=LR.predict(X_test)
print("Performance Using InBuilt LogisticRegression Model On Test Data")
print(f1_score(y_test,y_pred))

Performance Using InBuilt LogisticRegression Model On Test Data
0.8387096774193549
