<a href="https://colab.research.google.com/github/vatsalvasani/CE155_ML/blob/main/LAB%2003/CE155_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **EXERCISE - 3**

**1. Naive Bayes Classifier**

### ***1) IMPORT LIBRARIES***

In [315]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

### ***2) PREPARE DATASET***

In [316]:
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast','Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']
temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

### ***3) DIGITIZE THE DATA SET USING ENCODING***

In [317]:
le = preprocessing.LabelEncoder()
weather_encoded=le.fit_transform(weather)
temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)
print("Weather:" ,weather_encoded)
print("Temp:",temp_encoded)
print("Play:",label)

Weather: [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


### ***4) MERGE DIFFRENT FEATURES TO PREPARE DATASET***

In [318]:
#Combinig weather and temp into single listof tuples
features=tuple(zip(weather_encoded,temp_encoded))
print("Features:",features)

Features: ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


### ***5) CREATE A CLASSIFIER***

In [319]:
model=MultinomialNB()
# Train the model using the training sets
model.fit(features,label)

MultinomialNB()

### ***6) PREDICT OUTPUT FOR NEW DATA***

In [320]:
predicted= model.predict([[2,2]]) # 0:Overcast, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


# **Exercise:**

### ***1) WILL YOU PLAY IF TEMP IS HOT AND WEATHER IS OVERCAST***

In [321]:
predicted= model.predict([[0,1]]) # 0:Overcast, 1:Hot
print("Predicted Value:", predicted)

Predicted Value: [1]


### ***2) WILL YOU PLAY IF TEMP IS MILD AND WEATHER IS SUNNY***

In [322]:
predicted= model.predict([[2,2]]) # 2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


# **3_NB_Classifier_Iris_3Classes**

Task : 1 :- Try the algo on Dataset3 - LabelEncoding of features:and Train test Division 95%-5%

Questions: For Task - 1

(1) What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Nor-
mal’, and Wind = ’False’?

(2) What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’,
and Wind = ’True’?

(3) Accuracy , precision and recall of both Models?

In [323]:
#Import scikit-learn dataset library
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
import pandas as pd
from sklearn import preprocessing

In [324]:
from google.colab import drive
drive.mount("/content/drive")
datasets = pd.read_csv('/content/drive/MyDrive/sem 6/ML/LAB 3/Dataset3.csv')
datasets

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Outlook Temp Wind  Humidity  Class
0        R    H    F         1      0
1        R    H    T         2      0
2        O    H    F         1      1
3        R    M    F         1      1
4        S    C    F         1      1
5        O    C    T         0      0
6        O    C    T         1      1
7        R    M    F         1      0
8        O    C    F         0      1
9        S    M    F         2      1
10       R    C    T         2      0
11       O    M    T         0      1
12       O    H    F         1      1
13       S    M    T         1      0

In [325]:
features = datasets.iloc[:,0:4].values
features

array([['R', 'H', 'F', 1],
       ['R', 'H', 'T', 2],
       ['O', 'H', 'F', 1],
       ['R', 'M', 'F', 1],
       ['S', 'C', 'F', 1],
       ['O', 'C', 'T', 0],
       ['O', 'C', 'T', 1],
       ['R', 'M', 'F', 1],
       ['O', 'C', 'F', 0],
       ['S', 'M', 'F', 2],
       ['R', 'C', 'T', 2],
       ['O', 'M', 'T', 0],
       ['O', 'H', 'F', 1],
       ['S', 'M', 'T', 1]], dtype=object)

In [326]:
le = preprocessing.LabelEncoder()
features[:,0] = le.fit_transform(features[:,0])
features[:,1] = le.fit_transform(features[:,1])
features[:,2] = le.fit_transform(features[:,2])

In [327]:
features

array([[1, 1, 0, 1],
       [1, 1, 1, 2],
       [0, 1, 0, 1],
       [1, 2, 0, 1],
       [2, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [1, 2, 0, 1],
       [0, 0, 0, 0],
       [2, 2, 0, 2],
       [1, 0, 1, 2],
       [0, 2, 1, 0],
       [0, 1, 0, 1],
       [2, 2, 1, 1]], dtype=object)

In [328]:
label = datasets.iloc[:,4].values
label

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0])

### ***1) IMPORT LIBRARIES OR MODULES***

In [329]:
from sklearn.model_selection import train_test_split
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(features,
label, test_size = 0.05, random_state = 155)
print("Traing data : \n",data_train)
print("\nTesting data : \n",data_test)
print("\nTarget train : \n",target_train)
print("\nTarget test : \n",target_test)

Traing data : 
 [[0 2 1 0]
 [1 0 1 2]
 [0 0 0 0]
 [0 1 0 1]
 [1 2 0 1]
 [1 1 1 2]
 [0 0 1 1]
 [2 2 1 1]
 [0 0 1 0]
 [1 1 0 1]
 [1 2 0 1]
 [2 2 0 2]
 [2 0 0 1]]

Testing data : 
 [[0 1 0 1]]

Target train : 
 [1 0 1 1 1 0 1 0 0 0 0 1 1]

Target test : 
 [1]


### ***2) TRAIN THE MODEL***

In [330]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)
target_pred

array([1])

### ***1) WHAT WILL BE THE VALUE OF PLAY IF OUTLOOK IS RAINY,TEMP IS MILD AND HUMIDITY IS NORMAL AND WIND IS FALSE***

In [331]:
predicted = gnb.predict([[1,2,0,1]])
prob = gnb.predict_proba([[1,2,0,1]])
print(predicted)
prob

[1]


array([[0.3451965, 0.6548035]])

### ***2) WHAT WILL BE THE VALUE OF PLAY IF OUTLOOK IS SUNNY,TEMP IS COOL AND HUMIDITY IS HIGH AND WIND IS TRUE***

In [332]:
predicted1 = gnb.predict([[2,0,1,2]])
prob1 = gnb.predict_proba([[2,0,1,2]])
print(predicted1)
prob1

[0]


array([[0.82376314, 0.17623686]])

### ***3) ACCURACY,PRECISION AND RECALL OF BOTH MODELS***

In [333]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 1.0


In [334]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[1]])

In [335]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1.]
recall: [1.]


## Task : 2 :- Apply algorithm on breast cancer wisconsin dataset - One Hot Encoding of features: and Train test Division 50%-50%

In [336]:
from sklearn import datasets

breast_cancer = datasets.load_breast_cancer()
X = breast_cancer.data
y= breast_cancer.target

In [337]:
feature_names = breast_cancer.feature_names
target_names = breast_cancer.target_names
print("Feature names:", feature_names)
print()
print("Target names:", target_names)
print()
print("\nFirst 10 rows of X:\n", X[:10])

Feature names: ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']

Target names: ['malignant' 'benign']


First 10 rows of X:
 [[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e

### ***1) IMPORT LIBRARIES OR MODULES***

In [338]:
from sklearn.model_selection import train_test_split

#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(X,
y, test_size = 0.5, random_state = 155)

### ***2) TRAIN THE MODEL***

In [339]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)
target_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1])

### ***3) IMPORT SCIKIT-LEARN METRICS FOR ACCURACY CALCULATION***

In [340]:
from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.9508771929824561


### ***4) IMPORT CONFUSION MATRIX***

In [341]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[ 84,  11],
       [  3, 187]])

In [342]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.96551724 0.94444444]
recall: [0.88421053 0.98421053]
