<a href="https://colab.research.google.com/github/vatsalvasani/CE155_ML/blob/main/LAB%204/CE155_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **LAB 04**
## EXERCISE 1

1) Input (temp, rainfall, humidity)

In [ ]:
import numpy as np
import torch
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

2) Target (apples)

In [ ]:
targets = np.array([[56], 
                    [81], 
                    [119], 
                    [22], 
                    [103]], dtype='float32')

3) Convert inputs and targets to tensors

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


4) Weights and biases

In [ ]:
w = torch.randn(3, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
print(w)
print(b)

tensor([[ 0.1796],
        [-1.7677],
        [-1.2212]], requires_grad=True)
tensor([-1.6109], requires_grad=True)


5) Define The Model

In [ ]:
def model(x):
    return x @ w + b

6) Generate predictions

In [ ]:
preds = model(inputs)
print(preds)

tensor([[-159.4425],
        [-218.9748],
        [-293.6802],
        [-104.4817],
        [-244.3952]], grad_fn=<AddBackward0>)


7) Compare With Targets

In [ ]:
print(targets)

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


8) MSE Loss

In [ ]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [ ]:
loss = mse(preds, targets)
print(loss)

tensor(88677.2656, grad_fn=<DivBackward0>)


In [ ]:
loss.backward()

9) Compute Grediants

In [ ]:
print(w)
print(w.grad)

tensor([[ 0.1796],
        [-1.7677],
        [-1.2212]], requires_grad=True)
tensor([[-46319.8320],
        [-53968.0859],
        [-32558.1387]])


In [ ]:
preds = model(inputs)
print(preds)

tensor([[-159.4425],
        [-218.9748],
        [-293.6802],
        [-104.4817],
        [-244.3952]], grad_fn=<AddBackward0>)


In [ ]:
loss = mse(preds, targets)
print(loss)

tensor(88677.2656, grad_fn=<DivBackward0>)


In [ ]:
loss.backward(retain_graph=True)
print(w.grad)
print(b.grad)

tensor([[-28939.9551],
        [-35244.4844],
        [-21014.6504]])
tensor([-354.5097])


In [ ]:
# with torch.no_grad():
#     w -= w.grad * 1e-5
#     b -= b.grad * 1e-5
#     w.grad.zero_()
#     b.grad.zero_()

In [ ]:
# print(w)
# # print(b)

tensor([[ 0.6434],
        [-1.2273],
        [-0.8951]], requires_grad=True)
tensor([-1.6053], requires_grad=True)


In [ ]:
# preds = model(inputs)
# loss = mse(preds, targets)
# print(loss)

tensor(38385.7578, grad_fn=<DivBackward0>)


In [ ]:
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    print(loss);
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

tensor(58.0744, grad_fn=<DivBackward0>)
tensor(57.4507, grad_fn=<DivBackward0>)
tensor(56.8395, grad_fn=<DivBackward0>)
tensor(56.2408, grad_fn=<DivBackward0>)
tensor(55.6541, grad_fn=<DivBackward0>)
tensor(55.0792, grad_fn=<DivBackward0>)
tensor(54.5158, grad_fn=<DivBackward0>)
tensor(53.9636, grad_fn=<DivBackward0>)
tensor(53.4223, grad_fn=<DivBackward0>)
tensor(52.8917, grad_fn=<DivBackward0>)
tensor(52.3714, grad_fn=<DivBackward0>)
tensor(51.8614, grad_fn=<DivBackward0>)
tensor(51.3612, grad_fn=<DivBackward0>)
tensor(50.8708, grad_fn=<DivBackward0>)
tensor(50.3898, grad_fn=<DivBackward0>)
tensor(49.9180, grad_fn=<DivBackward0>)
tensor(49.4552, grad_fn=<DivBackward0>)
tensor(49.0012, grad_fn=<DivBackward0>)
tensor(48.5556, grad_fn=<DivBackward0>)
tensor(48.1186, grad_fn=<DivBackward0>)
tensor(47.6897, grad_fn=<DivBackward0>)
tensor(47.2687, grad_fn=<DivBackward0>)
tensor(46.8556, grad_fn=<DivBackward0>)
tensor(46.4500, grad_fn=<DivBackward0>)
tensor(46.0518, grad_fn=<DivBackward0>)


In [ ]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(301.3375, grad_fn=<DivBackward0>)


In [ ]:
preds

tensor([[ 62.4229],
        [ 80.9189],
        [113.1646],
        [ 52.7116],
        [ 80.9054]], grad_fn=<AddBackward0>)

In [ ]:
targets


tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])